In [3]:
import pandas as pd

In [5]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [8]:

df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [9]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [10]:

df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [11]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [12]:
df['Age']

0    25
1    30
Name: Age, dtype: int64

In [13]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [15]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [16]:
df.iloc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [17]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [18]:
df[df['Age']>=25]

    Name  Age
0  Alice   25
1    Bob   30

In [19]:
df['Gender']=['F','M']

In [20]:
df.drop('Age', axis=1, inplace=True)

In [21]:
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [22]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [23]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [24]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [27]:
df.groupby['Gender']['Age'].mean()

TypeError: 'method' object is not subscriptable

In [28]:
df.groupby('Gender')['Age'].mean()

KeyError: 'Column not found: Age'

In [29]:
pd.merge(df1, df2, on='key')

NameError: name 'df1' is not defined

In [30]:
df['Age']=['25','30']

In [31]:
df.groupby('Gender')['Age'].mean()

TypeError: dtype 'str' does not support operation 'mean'

In [32]:
print(df)

    Name Gender Age
0  Alice      F  25
1    Bob      M  30

In [33]:
df.groupby('Gender')['Age'].mean()

TypeError: dtype 'str' does not support operation 'mean'

In [34]:
print(df.groupby('Gender')['Age'].mean())

TypeError: dtype 'str' does not support operation 'mean'

In [35]:
print(df.groupby('Gender')['Age'].mean())

TypeError: dtype 'str' does not support operation 'mean'

In [36]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Gender': ['F', 'M', 'M']}
df = pd.DataFrame(data)

print(df.groupby('Gender')['Age'].mean())

Gender
F    25.0
M    32.5
Name: Age, dtype: float64

In [37]:
pd.merge(df1, df2, on='key')

NameError: name 'df1' is not defined

In [38]:
df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'key': [1, 2, 4],
    'Score': [85, 90, 95]
})

merged = pd.merge(df1, df2, on='key')
print(merged)

   key   Name  Score
0    1  Alice     85
1    2    Bob     90

In [40]:
df1.join(df2)

ValueError: columns overlap but no suffix specified: Index(['key'], dtype='str')

In [44]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob']}, index=[0,1])
df2 = pd.DataFrame({'Score': [85, 90]}, index=[0,1])

joined = df1.join(df2)
print(joined)

    Name  Score
0  Alice     85
1    Bob     90

In [45]:
df = pd.read_csv('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [46]:
df.sort_values('Age')

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M

In [47]:
df.to_csv('data.csv', index=False)

In [48]:
df2 = pd.read_csv('data.csv')
print(df2)

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M

In [49]:
df['Age'].apply(lambda x: x+1)

0    26
1    31
2    36
Name: Age, dtype: int64

In [50]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

In [51]:
df['Age'].value_counts()

Age
25    1
30    1
35    1
Name: count, dtype: int64